import type { ArtifactModelDefinition } from "@/features/artifacts/types";

export const artifactModelDefinitions: ArtifactModelDefinition[] = [
  {
    kind: "account",
    category: "accounts",
    label: "Account",
    description: "User account, profile, or service identity.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "username", label: "Username", type: "string" },
      { key: "displayName", label: "Display name", type: "string" },
      { key: "email", label: "Email", type: "string" },
      { key: "phone", label: "Phone", type: "string" },
      { key: "service", label: "Service", type: "string" },
      { key: "identifier", label: "Identifier", type: "string" },
    ],
  },
  {
    kind: "application",
    category: "applications",
    label: "Application",
    description: "Installed application or package.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "name", label: "Name", type: "string", required: true },
      { key: "packageName", label: "Package", type: "string" },
      { key: "version", label: "Version", type: "string" },
      { key: "vendor", label: "Vendor", type: "string" },
      { key: "installedAt", label: "Installed", type: "datetime" },
      { key: "lastUsedAt", label: "Last used", type: "datetime" },
    ],
  },
  {
    kind: "browser_history",
    category: "browser",
    label: "Browser History",
    description: "Visited URL or browser navigation event.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "url", label: "URL", type: "string", required: true },
      { key: "title", label: "Title", type: "string" },
      { key: "visitCount", label: "Visits", type: "number" },
      { key: "visitedAt", label: "Visited", type: "datetime" },
      { key: "browser", label: "Browser", type: "string" },
    ],
  },
  {
    kind: "call",
    category: "calls",
    label: "Call",
    description: "Call log entry.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "direction", label: "Direction", type: "string" },
      { key: "phone", label: "Phone", type: "string" },
      { key: "contactName", label: "Contact", type: "string" },
      { key: "startedAt", label: "Started", type: "datetime" },
      { key: "durationSeconds", label: "Duration", type: "number" },
    ],
  },
  {
    kind: "contact",
    category: "contacts",
    label: "Contact",
    description: "Person, organization, or address book record.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "name", label: "Name", type: "string", required: true },
      { key: "phones", label: "Phones", type: "string[]" },
      { key: "emails", label: "Emails", type: "string[]" },
      { key: "organization", label: "Organization", type: "string" },
      { key: "notes", label: "Notes", type: "string" },
    ],
  },
  {
    kind: "credential",
    category: "credentials",
    label: "Credential",
    description: "Credential indicator without storing raw secrets.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "username", label: "Username", type: "string" },
      { key: "service", label: "Service", type: "string" },
      { key: "url", label: "URL", type: "string" },
      { key: "secretType", label: "Secret type", type: "string" },
      { key: "secretPreview", label: "Secret preview", type: "string" },
    ],
  },
  {
    kind: "file",
    category: "files",
    label: "File",
    description: "File metadata or hash result.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "path", label: "Path", type: "string", required: true },
      { key: "name", label: "Name", type: "string" },
      { key: "extension", label: "Extension", type: "string" },
      { key: "size", label: "Size", type: "number" },
      { key: "sha256", label: "SHA-256", type: "string" },
      { key: "mimeType", label: "MIME type", type: "string" },
    ],
  },
  {
    kind: "location",
    category: "locations",
    label: "Location",
    description: "Geographic coordinate with optional accuracy.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "latitude", label: "Latitude", type: "number", required: true },
      { key: "longitude", label: "Longitude", type: "number", required: true },
      { key: "altitude", label: "Altitude", type: "number" },
      { key: "accuracyMeters", label: "Accuracy", type: "number" },
      { key: "recordedAt", label: "Recorded", type: "datetime" },
      { key: "sourceApp", label: "Source app", type: "string" },
    ],
  },
  {
    kind: "media",
    category: "media",
    label: "Media",
    description: "Image, video, or audio file.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "path", label: "Path", type: "string", required: true },
      { key: "mediaType", label: "Media type", type: "string" },
      { key: "createdAt", label: "Created", type: "datetime" },
      { key: "width", label: "Width", type: "number" },
      { key: "height", label: "Height", type: "number" },
      { key: "durationSeconds", label: "Duration", type: "number" },
    ],
  },
  {
    kind: "message",
    category: "messages",
    label: "Message",
    description: "SMS, chat, email, or app message.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "conversationId", label: "Conversation", type: "string" },
      { key: "sender", label: "Sender", type: "string" },
      { key: "recipients", label: "Recipients", type: "string[]" },
      { key: "body", label: "Body", type: "string" },
      { key: "sentAt", label: "Sent", type: "datetime" },
      { key: "receivedAt", label: "Received", type: "datetime" },
      { key: "service", label: "Service", type: "string" },
    ],
  },
  {
    kind: "note",
    category: "notes",
    label: "Note",
    description: "Plain text note or memo.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "title", label: "Title", type: "string" },
      { key: "body", label: "Body", type: "string", required: true },
      { key: "createdAt", label: "Created", type: "datetime" },
      { key: "modifiedAt", label: "Modified", type: "datetime" },
    ],
  },
  {
    kind: "system",
    category: "system",
    label: "System",
    description: "System setting, property, or configuration value.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "key", label: "Key", type: "string", required: true },
      { key: "value", label: "Value", type: "string", required: true },
      { key: "namespace", label: "Namespace", type: "string" },
    ],
  },
  {
    kind: "timeline_event",
    category: "timeline",
    label: "Timeline Event",
    description: "Timestamped event for timeline correlation.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "occurredAt", label: "Occurred", type: "datetime", required: true },
      { key: "eventType", label: "Event type", type: "string", required: true },
      { key: "actor", label: "Actor", type: "string" },
      { key: "target", label: "Target", type: "string" },
    ],
  },
  {
    kind: "record",
    category: "other",
    label: "Generic Record",
    description: "Fallback model for plugin-specific records.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "fields", label: "Fields", type: "json", required: true },
    ],
  },
];

export const artifactModelsByKind = new Map(
  artifactModelDefinitions.map((definition) => [definition.kind, definition]),
);
