import type { ArtifactModelDefinition } from "@/features/artifacts/types";

export const artifactModelDefinitions: ArtifactModelDefinition[] = [
  {
    kind: "account",
    category: "accounts",
    label: "Account",
    description: "User account, profile, or service identity.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "username", label: "Username", type: "string" },
      { key: "displayName", label: "Display name", type: "string" },
      { key: "email", label: "Email", type: "string" },
      { key: "phone", label: "Phone", type: "string" },
      { key: "service", label: "Service", type: "string" },
      { key: "identifier", label: "Identifier", type: "string" },
    ],
  },
  {
    kind: "application",
    category: "applications",
    label: "Application",
    description: "Installed application or package.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "name", label: "Name", type: "string", required: true },
      { key: "packageName", label: "Package", type: "string" },
      { key: "version", label: "Version", type: "string" },
      { key: "vendor", label: "Vendor", type: "string" },
      { key: "installedAt", label: "Installed", type: "datetime" },
      { key: "lastUsedAt", label: "Last used", type: "datetime" },
    ],
  },
  {
    kind: "browser_history",
    category: "browser",
    label: "Browser History",
    description: "Visited URL or browser navigation event.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "url", label: "URL", type: "string", required: true },
      { key: "title", label: "Title", type: "string" },
      { key: "visitCount", label: "Visits", type: "number" },
      { key: "visitedAt", label: "Visited", type: "datetime" },
      { key: "browser", label: "Browser", type: "string" },
    ],
  },
  {
    kind: "call",
    category: "calls",
    label: "Call",
    description: "Call log entry.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "direction", label: "Direction", type: "string" },
      { key: "phone", label: "Phone", type: "string" },
      { key: "contactName", label: "Contact", type: "string" },
      { key: "startedAt", label: "Started", type: "datetime" },
      { key: "durationSeconds", label: "Duration", type: "number" },
    ],
  },
  {
    kind: "contact",
    category: "contacts",
    label: "Contact",
    description: "Person, organization, or address book record.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "name", label: "Name", type: "string", required: true },
      { key: "phones", label: "Phones", type: "string[]" },
      { key: "emails", label: "Emails", type: "string[]" },
      { key: "organization", label: "Organization", type: "string" },
      { key: "notes", label: "Notes", type: "string" },
    ],
  },
  {
    kind: "credential",
    category: "credentials",
    label: "Credential",
    description: "Credential indicator without storing raw secrets.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "username", label: "Username", type: "string" },
      { key: "service", label: "Service", type: "string" },
      { key: "url", label: "URL", type: "string" },
      { key: "secretType", label: "Secret type", type: "string" },
      { key: "secretPreview", label: "Secret preview", type: "string" },
    ],
  },
  {
    kind: "file",
    category: "files",
    label: "File",
    description: "File metadata or hash result.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "path", label: "Path", type: "string", required: true },
      { key: "name", label: "Name", type: "string" },
      { key: "extension", label: "Extension", type: "string" },
      { key: "size", label: "Size", type: "number" },
      { key: "sha256", label: "SHA-256", type: "string" },
      { key: "mimeType", label: "MIME type", type: "string" },
    ],
  },
  {
    kind: "location",
    category: "locations",
    label: "Location",
    description: "Geographic coordinate with optional accuracy.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "latitude", label: "Latitude", type: "number", required: true },
      { key: "longitude", label: "Longitude", type: "number", required: true },
      { key: "altitude", label: "Altitude", type: "number" },
      { key: "accuracyMeters", label: "Accuracy", type: "number" },
      { key: "recordedAt", label: "Recorded", type: "datetime" },
      { key: "sourceApp", label: "Source app", type: "string" },
    ],
  },
  {
    kind: "media",
    category: "media",
    label: "Media",
    description: "Image, video, or audio file.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "path", label: "Path", type: "string", required: true },
      { key: "mediaType", label: "Media type", type: "string" },
      { key: "createdAt", label: "Created", type: "datetime" },
      { key: "width", label: "Width", type: "number" },
      { key: "height", label: "Height", type: "number" },
      { key: "durationSeconds", label: "Duration", type: "number" },
    ],
  },
  {
    kind: "message",
    category: "messages",
    label: "Message",
    description: "SMS, chat, email, or app message.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "conversationId", label: "Conversation", type: "string" },
      { key: "sender", label: "Sender", type: "string" },
      { key: "recipients", label: "Recipients", type: "string[]" },
      { key: "body", label: "Body", type: "string" },
      { key: "sentAt", label: "Sent", type: "datetime" },
      { key: "receivedAt", label: "Received", type: "datetime" },
      { key: "service", label: "Service", type: "string" },
    ],
  },
  {
    kind: "note",
    category: "notes",
    label: "Note",
    description: "Plain text note or memo.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "title", label: "Title", type: "string" },
      { key: "body", label: "Body", type: "string", required: true },
      { key: "createdAt", label: "Created", type: "datetime" },
      { key: "modifiedAt", label: "Modified", type: "datetime" },
    ],
  },
  {
    kind: "system",
    category: "system",
    label: "System",
    description: "System setting, property, or configuration value.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "key", label: "Key", type: "string", required: true },
      { key: "value", label: "Value", type: "string", required: true },
      { key: "namespace", label: "Namespace", type: "string" },
    ],
  },
  {
    kind: "timeline_event",
    category: "timeline",
    label: "Timeline Event",
    description: "Timestamped event for timeline correlation.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "occurredAt", label: "Occurred", type: "datetime", required: true },
      { key: "eventType", label: "Event type", type: "string", required: true },
      { key: "actor", label: "Actor", type: "string" },
      { key: "target", label: "Target", type: "string" },
    ],
  },
  {
    kind: "sms",
    category: "messages",
    label: "SMS",
    description: "Short message service message.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "conversationId", label: "Conversation", type: "string" },
      { key: "sender", label: "Sender", type: "string" },
      { key: "recipients", label: "Recipients", type: "string[]" },
      { key: "body", label: "Body", type: "string" },
      { key: "sentAt", label: "Sent", type: "datetime" },
      { key: "receivedAt", label: "Received", type: "datetime" },
    ],
  },
  {
    kind: "email",
    category: "communications",
    label: "Email",
    description: "Email message node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "messageId", label: "Message ID", type: "string" },
      { key: "from", label: "From", type: "string" },
      { key: "to", label: "To", type: "string[]" },
      { key: "subject", label: "Subject", type: "string" },
      { key: "sentAt", label: "Sent", type: "datetime" },
      { key: "receivedAt", label: "Received", type: "datetime" },
    ],
  },
  {
    kind: "mms",
    category: "messages",
    label: "MMS",
    description: "Multimedia message node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "conversationId", label: "Conversation", type: "string" },
      { key: "sender", label: "Sender", type: "string" },
      { key: "recipients", label: "Recipients", type: "string[]" },
      { key: "attachments", label: "Attachments", type: "string[]" },
      { key: "sentAt", label: "Sent", type: "datetime" },
    ],
  },
  {
    kind: "chat",
    category: "communications",
    label: "Chat",
    description: "Chat conversation node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "conversationId", label: "Conversation", type: "string" },
      { key: "participants", label: "Participants", type: "string[]" },
      { key: "service", label: "Service", type: "string" },
      { key: "startedAt", label: "Started", type: "datetime" },
      { key: "lastMessageAt", label: "Last message", type: "datetime" },
    ],
  },
  {
    kind: "instant_message",
    category: "messages",
    label: "Instant Message",
    description: "Single instant-message node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "conversationId", label: "Conversation", type: "string" },
      { key: "sender", label: "Sender", type: "string" },
      { key: "recipients", label: "Recipients", type: "string[]" },
      { key: "body", label: "Body", type: "string" },
      { key: "sentAt", label: "Sent", type: "datetime" },
    ],
  },
  {
    kind: "user_account",
    category: "accounts",
    label: "User Account",
    description: "User account or profile node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "username", label: "Username", type: "string" },
      { key: "displayName", label: "Display name", type: "string" },
      { key: "email", label: "Email", type: "string" },
      { key: "service", label: "Service", type: "string" },
      { key: "identifier", label: "Identifier", type: "string" },
    ],
  },
  {
    kind: "voice_mail",
    category: "communications",
    label: "VoiceMail",
    description: "Voicemail message node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "phone", label: "Phone", type: "string" },
      { key: "contactName", label: "Contact", type: "string" },
      { key: "transcript", label: "Transcript", type: "string" },
      { key: "receivedAt", label: "Received", type: "datetime" },
      { key: "durationSeconds", label: "Duration", type: "number" },
    ],
  },
  {
    kind: "calendar_entry",
    category: "calendar",
    label: "Calendar Entry",
    description: "Calendar appointment or reminder node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "title", label: "Title", type: "string" },
      { key: "startsAt", label: "Starts", type: "datetime" },
      { key: "endsAt", label: "Ends", type: "datetime" },
      { key: "location", label: "Location", type: "string" },
      { key: "attendees", label: "Attendees", type: "string[]" },
    ],
  },
  {
    kind: "password",
    category: "credentials",
    label: "Password",
    description: "Password or password-derived credential node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "username", label: "Username", type: "string" },
      { key: "service", label: "Service", type: "string" },
      { key: "url", label: "URL", type: "string" },
      { key: "secretPreview", label: "Secret preview", type: "string" },
      { key: "storedAt", label: "Stored", type: "datetime" },
    ],
  },
  {
    kind: "journey",
    category: "journeys",
    label: "Journey",
    description: "Trip, route, or movement node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "startedAt", label: "Started", type: "datetime" },
      { key: "endedAt", label: "Ended", type: "datetime" },
      { key: "origin", label: "Origin", type: "string" },
      { key: "destination", label: "Destination", type: "string" },
      { key: "points", label: "Points", type: "json" },
    ],
  },
  {
    kind: "installed_application",
    category: "applications",
    label: "Installed Application",
    description: "Installed application node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "name", label: "Name", type: "string" },
      { key: "packageName", label: "Package", type: "string" },
      { key: "version", label: "Version", type: "string" },
      { key: "vendor", label: "Vendor", type: "string" },
      { key: "installedAt", label: "Installed", type: "datetime" },
    ],
  },
  {
    kind: "cookie",
    category: "browser",
    label: "Cookie",
    description: "Browser or application cookie node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "host", label: "Host", type: "string" },
      { key: "name", label: "Name", type: "string" },
      { key: "path", label: "Path", type: "string" },
      { key: "createdAt", label: "Created", type: "datetime" },
      { key: "expiresAt", label: "Expires", type: "datetime" },
    ],
  },
  {
    kind: "application_usage",
    category: "applications",
    label: "Application Usage",
    description: "Application usage event node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "application", label: "Application", type: "string" },
      { key: "packageName", label: "Package", type: "string" },
      { key: "startedAt", label: "Started", type: "datetime" },
      { key: "endedAt", label: "Ended", type: "datetime" },
      { key: "durationSeconds", label: "Duration", type: "number" },
    ],
  },
  {
    kind: "visited_page",
    category: "browser",
    label: "Visited Page",
    description: "Visited web page node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "url", label: "URL", type: "string" },
      { key: "title", label: "Title", type: "string" },
      { key: "visitedAt", label: "Visited", type: "datetime" },
      { key: "browser", label: "Browser", type: "string" },
    ],
  },
  {
    kind: "dictionary_word",
    category: "search",
    label: "Dictionary Word",
    description: "Learned or suggested dictionary word node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "word", label: "Word", type: "string" },
      { key: "language", label: "Language", type: "string" },
      { key: "learnedAt", label: "Learned", type: "datetime" },
      { key: "usageCount", label: "Usage count", type: "number" },
    ],
  },
  {
    kind: "web_bookmark",
    category: "browser",
    label: "Web Bookmark",
    description: "Browser bookmark node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "url", label: "URL", type: "string" },
      { key: "title", label: "Title", type: "string" },
      { key: "folder", label: "Folder", type: "string" },
      { key: "createdAt", label: "Created", type: "datetime" },
    ],
  },
  {
    kind: "shared_file",
    category: "files",
    label: "Shared File",
    description: "File sharing node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "path", label: "Path", type: "string" },
      { key: "name", label: "Name", type: "string" },
      { key: "sharedWith", label: "Shared with", type: "string[]" },
      { key: "sharedAt", label: "Shared", type: "datetime" },
      { key: "service", label: "Service", type: "string" },
    ],
  },
  {
    kind: "bluetooth_device",
    category: "networks",
    label: "Bluetooth Device",
    description: "Bluetooth device node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "name", label: "Name", type: "string" },
      { key: "address", label: "Address", type: "string" },
      { key: "pairedAt", label: "Paired", type: "datetime" },
      { key: "lastConnectedAt", label: "Last connected", type: "datetime" },
    ],
  },
  {
    kind: "map",
    category: "maps",
    label: "Map",
    description: "Map view, layer, or provider node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "name", label: "Name", type: "string" },
      { key: "provider", label: "Provider", type: "string" },
      { key: "centerLatitude", label: "Center latitude", type: "number" },
      { key: "centerLongitude", label: "Center longitude", type: "number" },
      { key: "bounds", label: "Bounds", type: "json" },
    ],
  },
  {
    kind: "searched_item",
    category: "search",
    label: "Searched Item",
    description: "Search query or searched item node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "query", label: "Query", type: "string" },
      { key: "searchedAt", label: "Searched", type: "datetime" },
      { key: "application", label: "Application", type: "string" },
      { key: "url", label: "URL", type: "string" },
    ],
  },
  {
    kind: "wireless_network",
    category: "networks",
    label: "Wireless Network",
    description: "Wi-Fi or wireless network node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "ssid", label: "SSID", type: "string" },
      { key: "bssid", label: "BSSID", type: "string" },
      { key: "security", label: "Security", type: "string" },
      { key: "lastConnectedAt", label: "Last connected", type: "datetime" },
    ],
  },
  {
    kind: "notification",
    category: "system",
    label: "Notification",
    description: "Notification event node.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "application", label: "Application", type: "string" },
      { key: "title", label: "Title", type: "string" },
      { key: "body", label: "Body", type: "string" },
      { key: "receivedAt", label: "Received", type: "datetime" },
    ],
  },
  {
    kind: "carved_string",
    category: "search",
    label: "Carved String",
    description: "String carved from unstructured bytes.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "value", label: "Value", type: "string" },
      { key: "encoding", label: "Encoding", type: "string" },
      { key: "offset", label: "Offset", type: "number" },
      { key: "length", label: "Length", type: "number" },
    ],
  },
  {
    kind: "powering_event",
    category: "system",
    label: "Powering Event",
    description: "Power on, shutdown, reboot, sleep, or wake event.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "eventType", label: "Event type", type: "string" },
      { key: "occurredAt", label: "Occurred", type: "datetime" },
      { key: "sourceApp", label: "Source app", type: "string" },
    ],
  },
  {
    kind: "record",
    category: "other",
    label: "Generic Record",
    description: "Fallback model for plugin-specific records.",
    fields: [
      { key: "label", label: "Label", type: "string", required: true },
      { key: "fields", label: "Fields", type: "json", required: true },
    ],
  },
];

export const artifactModelsByKind = new Map(
  artifactModelDefinitions.map((definition) => [definition.kind, definition]),
);
