import type { DataSourcePlugin } from "@/features/datasources/types";

export const dataSourcePlugins: DataSourcePlugin[] = [
  {
    id: "file-metadata",
    name: "File Metadata",
    description: "Collect size, timestamps, extension, and filesystem attributes.",
    type: "other",
    mode: "each_file",
    entry: "plugin.py",
    function: "run",
  },
  {
    id: "keyword-scanner",
    name: "Keyword Scanner",
    description: "Index plain text and binary strings for case search.",
    type: "other",
    mode: "path_regex",
    pathRegex: "(?i).*\\.(txt|log|json|xml|csv)$",
    entry: "plugin.py",
    function: "run",
  },
  {
    id: "string-extractor",
    name: "String Extractor",
    description: "Extract printable strings from unknown and binary files.",
    type: "other",
    mode: "each_file",
    entry: "plugin.py",
    function: "run",
  },
  {
    id: "image-metadata",
    name: "Image Metadata",
    description: "Read EXIF and basic image properties.",
    type: "other",
    mode: "path_regex",
    pathRegex: "(?i).*\\.(jpg|jpeg|png|heic)$",
    entry: "plugin.py",
    function: "run",
  },
  {
    id: "sqlite-parser",
    name: "SQLite Parser",
    description: "Inspect SQLite databases and known application stores.",
    type: "other",
    mode: "path_regex",
    pathRegex: "(?i).*\\.(sqlite|sqlite3|db)$",
    entry: "plugin.py",
    function: "run",
  },
  {
    id: "browser-history",
    name: "Browser History",
    description: "Parse common Chromium and Firefox browsing artifacts.",
    type: "windows",
    mode: "path_regex",
    pathRegex: "(?i).*(history|places\\.sqlite)$",
    entry: "plugin.py",
    function: "run",
  },
];
